name: Security

on:
  push:
    branches:
      - master
      - add-sbom-generation

  pull_request:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Semgrep
        run: semgrep scan --config auto